## Tensorflow fundamentals


## Creating tensor with cosntant tf.constant()

In [ ]:
 # install libs an setup configs
 %load_ext rich

In [2]:
import tensorflow as tf
from rich import print
print("version "+ tf.__version__)

version 2.17.0

```py
tf.constant(
    value, dtype=None, shape=None, name=&#x27;Const'
) -> Union[tf.Operation, ops._EagerTensorBase]

```

In [ ]:
# create a constant tensor
# Be aware of the type of data dtype=int32 by default

scalar = tf.constant(7)
scalar

# check the number of dimensions
scalar.ndim # its an rank 0, a scalar



0

In [ ]:
# lets create a vector
import numpy as np
array = np.array([1,2,3,4,5])
t_array = tf.constant(array)
t_array
t_array.ndim

1

In [ ]:
mat = np.array([[1,2,3],[1,2,3],[1,2,3]])
t_mat = tf.constant(mat)
t_mat


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [ ]:
# ndimensional tensor rank ?

tensor = tf.constant(
   [[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
   [[1,2,3,4],[1,2,3,4],[1,2,3,4]] ]
)

print(tensor.ndim)
print(tensor)


3

tf.Tensor(
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]], shape=(2, 3, 4), dtype=int32)

## Creating tensor with variable tf.Variable()

```py

tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)

```

In [ ]:
# Variable is changeble tensor, its opposite of cosntant

changeble = tf.Variable([
   [1,2,3,4] ,
   [5,6,7,8]
], dtype=np.float16) # change the dtype

changeble


<tf.Variable 'Variable:0' shape=(2, 4) dtype=float16, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float16)>

In [ ]:
# Assign is used to change the values from a tensor, they use the same way of slice arrays as numpy
changeble[0:,1].assign(0) # from the line 0 util the end '0:end' , on the column ' 1 '


<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=float16, numpy=
array([[1., 0., 3., 4.],
       [5., 0., 7., 8.]], dtype=float16)>

## Create random tensors

Rarely in practice you need to decide whether to use constant or variable, tf will automatically decide it for you. However, if in doubt,use constant and change it later if needed

Random tensor are filled with abitrary numbers

In [ ]:
random_t = tf.random.Generator.from_seed(42) # set seed for reprodutibility
r_1 = random_t.normal(shape=(3,3), dtype=np.float16)
r_1
r_2 = random_t.uniform(shape=(2,4), name="my random tensor")
r_2


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.5532898 , 0.05245876, 0.37663293, 0.350528  ],
       [0.44322133, 0.6576971 , 0.4425751 , 0.5878557 ]], dtype=float32)>

In [ ]:
# lets shuffle a tensor

not_shuffled_t = tf.constant([
    [1,2,3],
    [4,3,2],
    [2,3,1]
])

not_shuffled_t


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 3, 2],
       [2, 3, 1]], dtype=int32)>

In [ ]:
# The tensor is shuffled only in his firt dimension, that means only on line if we have 2 dimensions

shuffled_t = tf.random.shuffle(value = not_shuffled_t)
shuffled_t


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 1],
       [4, 3, 2]], dtype=int32)>

Tensor flow have few rules agains shuffle and radom seeds.
- check the [documentation](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) about.

In [ ]:
# Reproducible shuffle
tf.random.set_seed(42) # global seed 42
tf.random.shuffle(value = not_shuffled_t, seed=42) # operation level seed equals to global


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 3, 2],
       [2, 3, 1]], dtype=int32)>

## Other ways to make tensors

In [ ]:
# using numpy
a = np.ones(shape=(1,4), dtype=np.int32)
tf.Variable(a)

# or

# numpy.zeros(shape=(1,4))
tf.zeros(shape=(1,4)) # creating tensor of zeros using numpy buitin

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# changing shape
np_A = np.arange(0,64)
np_A

A = tf.constant(np_A)
A = tf.constant(value = A ,  shape=(4,4,4)) # 4^3 = 64 elements
A



<tf.Tensor: shape=(4, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])>

## Tensor attributes

In [ ]:
tf_attributes = tf.constant([1,2,3,4])

# shape

tf_attributes.shape
tf_attributes.ndim
# tf_attributes[0],  tf_attributes[1] ...
tf.size(tf_attributes)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
print(tf_attributes)
tf.ones(shape=(2,3))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## Indexing tensors
### Tensor can be indexeds just like python lists
- see more on [numpy slicing](https://numpy.org/doc/stable/user/basics.indexing.html)

In [ ]:
tensor_indexing = tf.zeros(shape=(2,3,4,5))

In [ ]:
# the first two elements of each dimension
# using the slice notation from numpy
# [start: stop: step]
#
            #   d4  d3  d2  d1
tensor_indexing[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the firt element from each dimension from each index except the last one
tensor_indexing[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor and add a new dimension

rank_2_t = tf.constant([[1,2,3],
                        [3,2,1]
                        ])

rank_2_t.shape, rank_2_t.ndim

(TensorShape([2, 3]), 2)

In [ ]:
# using tf.newaxis

rank_2_t[..., tf.newaxis]


<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[3],
        [2],
        [1]]], dtype=int32)>

In [ ]:
# expand dims
# modifie shape

tf.expand_dims(input = rank_2_t, axis=1)


<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[3, 2, 1]]], dtype=int32)>

In [ ]:
# trying reshape
# restricted by the number of elements inside of tensor

tf.reshape(tensor = rank_2_t, shape=(2,3,1))


<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[3],
        [2],
        [1]]], dtype=int32)>

## Manipulating tensors

- Basic elementwise operation
- Tensor operations
    - add
    - sub
    - div
    - mult

In [ ]:
# You can add new values to a tensor using add operator
tensor = tf.zeros(shape = (3,3))

# basic four operations
tensor + 10 , tensor -10, (tensor+ 10) / 10, tensor + 2 * 10

# the original tensor is unchanged!



(
    <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)>,
    <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-10., -10., -10.],
       [-10., -10., -10.],
       [-10., -10., -10.]], dtype=float32)>,
    <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>,
    <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]], dtype=float32)>
)

In [ ]:
# we can use builtin function to operat any tensor
# better to speedup on gpu,
# find more math operation on documentation

tf.add(tensor,10)
tf.multiply(tensor, 10)
tf.divide(tensor, 10)
tf.subtract(tensor, 10)



<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-10., -10., -10.],
       [-10., -10., -10.],
       [-10., -10., -10.]], dtype=float32)>

**Matrix operations**


In [ ]:
# Matrix multiplication
# the number of columns of the first op has to be equal
# of the number of lines of the second op

# mxn * mxn, m == n

vec_A = tf.constant(
    [1,2,3], shape=(3,1)
)
vec_A

mat_A = tf.constant([[1,2,3],
                    [5,6,6],
                    [5,6,7]
                     ])
mat_A
mat_B = tf.matmul(mat_A, vec_A)

mat_B


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[14],
       [35],
       [38]], dtype=int32)>

In [ ]:
# transpose a matrix
# reshape just shuffle the tensor around
# transpose shift axis

tf.transpose(mat_B) , tf.reshape(mat_B, shape=(3,1))


(
    <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[14, 35, 38]], dtype=int32)>,
    <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[14],
       [35],
       [38]], dtype=int32)>
)

In [ ]:
transposed_A = tf.constant([[1,2,3],[4,5,6]])

transposed_A, tf.reshape(transposed_A , shape=(3,2)), tf.transpose(transposed_A)



(
    <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>,
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>,
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>
)

In [ ]:
# Changing data type of a tensor

tensor = tf.constant([1,2,3,4])
tensor.dtype # default data type is int32

tf.cast(tensor, dtype=tf.float16)


<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>

## Aggregating tensors

- Aggregating tensor = condersiong them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values

D = tf.constant([-7,-10])

D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# create a large tensor

A = tf.constant(np.random.randint(0,100, size=50))

In [ ]:
A


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 75, 48, 63, 21, 98, 68, 47, 76, 11, 70, 78, 80,  3, 40, 46, 48,
       62, 74, 45, 17, 54, 82, 43, 24, 20, 29, 54, 49, 87, 45, 97, 48, 26,
       32, 92, 99, 30, 26, 71, 46, 43, 73, 19,  7, 16, 30, 18, 59, 60])>

In [ ]:
tf.size(A), A.ndim, A.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [ ]:
# find the minimum

tf.reduce_min(A), tf.reduce_max(A), tf.reduce_sum(A)

tf.math.reduce_variance(tf.cast(A, dtype=tf.float32))
tf.math.reduce_std(tf.cast(A, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.540682>

## Find the positional index maximum and minimum

In [ ]:
# find index of the positional maximum and minimum

tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.math.argmax(tensor)
tensor[tf.math.argmax(tensor)]

tensor[tf.math.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# squeezing a tensor


## Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Remove dimension of size 1
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

# One hot encoding tensors

- **Must be readed**
    - [Machine learning mastery](https://machinelearningmastery.com/one-hot-encoding-for-categorical-data/)



- A way to transform categorical classes on binary categorical number

In [ ]:
# simple example
indices = [0, 1, 2, 4]
depth = 4
tf.one_hot(indices, depth)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# specifie custom values

#tf.one_hot(..., on_value="custom value", off_value="custom valu")

## Explorando Tensors and Numpy

- Tensorflow tensor runs faster
- Numpy array can't run on a TPU as a tensor

In [ ]:
# The fundamental package for scientific computing with Python

J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor J to a Numpy array

J.numpy()

array([ 3.,  7., 10.])

## Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()


[
    PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
    PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
]

In [ ]:
!nvidia-smi

Fri Sep 13 14:06:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0              27W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Extra-curriculum exercise

